on: [push]

env:
  GO_VERSION: 1.20.x
  NODE_VERSION: 18.x

name: Test
jobs:
  build-exe:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install NSIS
      run: |
        iwr -useb get.scoop.sh -outfile 'install.ps1'
        .\install.ps1 -RunAsAdmin
        scoop update
        scoop bucket add extras
        scoop install nsis
    - name: Print NSIS version
      run: makensis -VERSION
    - uses: actions/checkout@v3
    - name: Insatll wails
      run: |
       go install github.com/wailsapp/wails/v2/cmd/wails@latest
    - name: build
      run: |
       wails build -nsis
   - uses: actions/upload-artifact@v3
      with:
        name: build-files
        path:
           .\buid\bin\OmniSSHAgent.exe
           .\buid\bin\OmniSSHAgent-amd64-installer.exe
      - name: show info
        run: |
          echo "ls build/bin"  >> $GITHUB_STEP_SUMMARY
          ls "build/bin">> $GITHUB_STEP_SUMMARY
  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    needs: [build-exe]
    steps:
      - uses: actions/checkout@v3
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          body_path: release.md
          fail_on_unmatched_files: true
          generate_release_notes: true
          append_body: true
          files: |
            .build-files/*.exe
